# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Mazk
tagline:             'Corner'
description:         '独处角落静书生活'
url:                 /
baseurl:             /
paginate:            8

# About/contact
author:
  name:              mazk
  disqus:            mazk

# Custom vars
saying:              'Stand on the shoulders of giants, observing details of the world.'

# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]